# Site settings
title:       思圆笔记
email:       wudibiz(#)163.com
author:      pimgeek
description: "让思考转起来"
baseurl:     "/base"
url:         ""
duoshuo_url: "http://pimgeek.github.io"
source:      '_jksrc'
destination: 'base'

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: pimgeek

# Social icons
show_duoshuo: false
show_social_icons: false
github_username: pimgeek
stackoverflow_id:
twitter_username:
google_plus_id:
linkedin_username:
angellist_username:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    notes/:title.html
#paginate:     3
sass:
  compressed: true

# Collection 设定
collections:
  category:
    output: true
    permalink: category/:path/index.html
  notes:
    output: true
    permalink: notes/:title.html
